import { test, expect } from '@pageobjects/pageFixture';

/**
 * Test Suite: Automation Practice Form Submission
 * Generated by POM Generator Agent v2.0
 * Test Case ID: TC_001
 */
test.describe('Automation Practice Form - Student Registration', () => {

  test('TC_001: Verify successful submission of automation practice form with valid personal information', async ({ automationPracticeFormPage }) => {
    // Step 1: Navigate to form
    await automationPracticeFormPage.navigateTo();

    // Step 2: Enter first name
    await automationPracticeFormPage.fillFirstName('Kien Tuong');

    // Step 3: Enter last name
    await automationPracticeFormPage.fillLastName('Dang');

    // Step 4: Enter email address
    await automationPracticeFormPage.fillEmail('tuong.dangkien@gmail.com');

    // Step 5: Select gender - Male
    await automationPracticeFormPage.selectGenderMale();

    // Step 6: Enter mobile number
    await automationPracticeFormPage.fillMobile('0195808365');

    // Step 7: Enter date of birth - 07 Nov 1995
    await automationPracticeFormPage.fillDateOfBirth('07 Nov 1995');

    // Step 8: Select hobbies - Sports
    await automationPracticeFormPage.selectHobbySports();

    // Step 9: Select state - NCR
    await automationPracticeFormPage.selectState('NCR');

    // Step 10: Select city - Delhi
    await automationPracticeFormPage.selectCity('Delhi');

    // Step 11: Click submit button
    await automationPracticeFormPage.clickSubmit();

    // Step 12: Verify submission confirmation
    await automationPracticeFormPage.waitForConfirmationModal();

    // Assertion 1: Confirmation modal is visible
    const confirmationModal = automationPracticeFormPage.getConfirmationModal();
    await expect(confirmationModal).toBeVisible();
  });
});
