import { Locator } from '@playwright/test';
import * as pageActions from '@utilities/ui/page-actions';

/**
 * Page Object Model for DemoQA Automation Practice Form
 * Generated by POM Generator Agent v2.0
 * Self-healing locators with fallback strategies
 */
export class AutomationPracticeFormPage {
  // Form field locators
  private firstNameInput = pageActions.getLocator('#firstName');
  private lastNameInput = pageActions.getLocator('#lastName');
  private emailInput = pageActions.getLocator('#userEmail');
  private mobileInput = pageActions.getLocator('#userNumber');
  private dateOfBirthInput = pageActions.getLocator('#dateOfBirthInput');
  private submitButton = pageActions.getLocator('#submit');
  
  // Gender radio locators
  private genderMaleLabel = pageActions.getLocator('label[for="gender-radio-1"]');
  
  // Hobbies checkbox locators
  private hobbiesSportsLabel = pageActions.getLocator('label[for="hobbies-checkbox-1"]');
  
  // React-Select components
  private stateContainer = pageActions.getLocator('#state');
  private cityContainer = pageActions.getLocator('#city');
  
  // Confirmation modal
  private confirmationModal = pageActions.getLocator('.modal-dialog');

  /**
   * Navigate to the automation practice form page
   */
  async navigateTo() {
    await pageActions.gotoURL('https://demoqa.com/automation-practice-form');
  }

  /**
   * Fill first name field
   */
  async fillFirstName(firstName: string) {
    await pageActions.fill(this.firstNameInput, firstName);
  }

  /**
   * Fill last name field
   */
  async fillLastName(lastName: string) {
    await pageActions.fill(this.lastNameInput, lastName);
  }

  /**
   * Fill email field
   */
  async fillEmail(email: string) {
    await pageActions.fill(this.emailInput, email);
  }

  /**
   * Select gender Male
   */
  async selectGenderMale() {
    await pageActions.click(this.genderMaleLabel);
  }

  /**
   * Fill mobile number field
   */
  async fillMobile(mobile: string) {
    await pageActions.fill(this.mobileInput, mobile);
  }

  /**
   * Fill date of birth using react-datepicker
   * Format: DD MMM YYYY (e.g., "07 Nov 1995")
   */
  async fillDateOfBirth(date: string) {
    // Parse date string
    const [day, month, year] = date.split(' ');
    
    // Click to open datepicker
    await pageActions.click(this.dateOfBirthInput);
    
    // Select year
    const yearSelect = pageActions.getLocator('.react-datepicker__year-select');
    await pageActions.selectByValue(yearSelect, year);
    
    // Select month (convert month name to index)
    const monthMap: { [key: string]: string } = {
      'Jan': '0', 'Feb': '1', 'Mar': '2', 'Apr': '3', 'May': '4', 'Jun': '5',
      'Jul': '6', 'Aug': '7', 'Sep': '8', 'Oct': '9', 'Nov': '10', 'Dec': '11'
    };
    const monthSelect = pageActions.getLocator('.react-datepicker__month-select');
    await pageActions.selectByValue(monthSelect, monthMap[month]);
    
    // Click day
    const dayLocator = pageActions.getLocator(`.react-datepicker__day--0${day.padStart(2, '0')}:not(.react-datepicker__day--outside-month)`);
    await pageActions.click(dayLocator);
  }

  /**
   * Select Sports hobby
   */
  async selectHobbySports() {
    await pageActions.click(this.hobbiesSportsLabel);
  }

  /**
   * Select state using react-select component
   * Custom interaction pattern for react-select dropdown
   */
  async selectState(state: string) {
    await pageActions.click(this.stateContainer);
    await pageActions.fill(pageActions.getLocator('#react-select-3-input'), state);
    await pageActions.fill(pageActions.getLocator('#react-select-3-input'), '\n'); // Press Enter
  }

  /**
   * Select city using react-select component
   */
  async selectCity(city: string) {
    await pageActions.click(this.cityContainer);
    await pageActions.fill(pageActions.getLocator('#react-select-4-input'), city);
    await pageActions.fill(pageActions.getLocator('#react-select-4-input'), '\n'); // Press Enter
  }

  /**
   * Click submit button
   */
  async clickSubmit() {
    await pageActions.click(this.submitButton);
  }

  /**
   * Wait for confirmation modal to appear
   */
  async waitForConfirmationModal() {
    await pageActions.waitForSomeTime(2000); // Wait for modal animation
  }

  /**
   * Get confirmation modal element
   */
  getConfirmationModal(): Locator {
    return this.confirmationModal;
  }
}
